# Generated by Django 4.0.6 on 2022-07-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.TextField(default='http://'),
            preserve_default=False,
        ),
    ]
