# Generated by Django 4.0.6 on 2022-07-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_add_address_website_field_create_image_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=255),
        ),
    ]
