# Generated by Django 4.0.6 on 2022-07-24 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_add_ordering_to_category_add_website_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company_in_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='baseapp.company'),
        ),
    ]
