# Generated by Django 4.0.6 on 2022-07-24 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_category_options_alter_company_brand_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company_in_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='baseapp.company'),
        ),
    ]
