# Generated by Django 4.1 on 2022-08-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_alter_company_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='spots',
            field=models.PositiveIntegerField(verbose_name='How many spots or seats?'),
        ),
    ]
