# Generated by Django 4.1 on 2022-08-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registration_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=11),
        ),
    ]
