# Generated by Django 4.1 on 2022-08-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_alter_company_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='previous_brand_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
