# Generated by Django 4.1 on 2022-08-16 10:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0013_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
        migrations.AddField(
            model_name='company',
            name='entered_phone',
            field=models.CharField(max_length=255),
        ),
    ]
