# Generated by Django 4.1 on 2022-08-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0015_company_latitude_company_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
