# Generated by Django 4.1 on 2022-08-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0016_alter_company_latitude_alter_company_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
    ]
